site_name: My Docs

theme: 
  name: "material"

nav:
  - index.md
  - cli_reference.md 
  - cargo_cli.md 
  - ripbin_cli.md 
  - ghidra_cli.md 
  - ida_cli.md 
  - profile_cli.md 
  - modify_cli.md 

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
    
markdown_extensions:
  - admonition
  - pymdownx.superfences


