site_name: My Docs

theme: 
  name: "material"

nav:
  - index.md
  - cli_reference.md 


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
    
markdown_extensions:
  - admonition
  - pymdownx.superfences


